### ISSUE TITLE
Unable to see the conversion - get NaN instead

### ISSUE THREAD

**Issue by callmekatootie** [ThomasKranitsas/tc-locale#1]
![image](https://cloud.githubusercontent.com/assets/2317133/19638336/1b13bf3a-99f1-11e6-8f8d-d43f197d12bf.png)

I installed the extension - The only setting I changed was to set the conversion to INR (Indian rupees) and then add a `Rs.` prefix.

**Comment by ThomasKranitsas** [comment]
Hm.. That's weird.. I just switched to INR in my settings and PACTs are displayed fine.. 
https://gyazo.com/13b056400de70e2d4b7ca84ae2082eab

Could you please post a screenshot of your settings? 
Mine looks like this: https://gyazo.com/d1a1b27751daea725eb72490b72b3f27

**Comment by ThomasKranitsas** [comment]
Do you see any error in console?

**Comment by callmekatootie** [comment]
Settings:

![image](https://cloud.githubusercontent.com/assets/2317133/19638472/be6a52b6-99f1-11e6-9ad6-8f401c896e6f.png)

I closed the browser and opened again - I still have the same issue.

No, I don't see any errors in console.

**Comment by ThomasKranitsas** [comment]
Can you please use a custom exchange rate to see if it's an issue with the Fixer API?

I guess the format of the payment in USD is `#,###.##` correct?

**Comment by callmekatootie** [comment]
Format is correct.

I tried custom exchange rate and I still have the same issue.

**Comment by ThomasKranitsas** [comment]
I'm closing this one as it has been fixed in version `1.0.2` of the extension.
Thank you for reporting it!
